# Generated by Django 3.0.6 on 2020-05-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('launch_date', models.DateTimeField(verbose_name='date launched')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('champ_type', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Champion')),
            ],
        ),
    ]
